// Shared portfolio catalogue. Keep product scope explicit; this is not a live availability list.
const rows: readonly (readonly [
  string,
  string,
  string,
  string,
  string,
  string,
])[] = [
  ["iq-practice-cloud", "IQ Practice Cloud", "Professional services", "Accountancy practice clients, staff, documents and work management", "documents", "confirmed"],
  ["ilmvero", "Ilmvero", "Education & careers", "School administration, staff, fees and campus operations", "coordination", "confirmed"],
  ["zivvo", "Zivvo", "Transport & logistics", "Motor dealer inventory, staff, sales and business operations", "commerce", "confirmed"],
  ["onyngo", "OnýnGo", "Food & hospitality", "Restaurant vendor operations, marketing and delivery coordination", "commerce", "confirmed"],
  ["bidlumo", "Bidlumo", "Commerce", "Live commerce seller inventory, fulfilment and business operations", "commerce", "confirmed"],

  ["tenderos", "Tendryva", "Professional services", "Tender discovery, bid pipelines and evidence coordination", "quotes", "confirmed"],
  ["konnevia", "Konnevia CRM", "Communications", "Customer inbox, sales pipelines and workspace operations", "inbox", "confirmed"],
  ["commerceops", "CommerceOps", "Commerce", "Seller research, product operations and commerce workspaces", "commerce", "confirmed"],
  ["recovra", "Recovra", "Professional services", "Revenue recovery evidence, invoices and approval workflows", "documents", "confirmed"],
  ["travel-agency-os", "Travel Agency OS", "Marketplaces", "Agency trips, departures, suppliers and team operations", "coordination", "confirmed"],
  ["empfangiq", "EmpfangIQ", "Communications", "Reception, appointments and customer service workflows", "inbox", "confirmed"],
  ["loungetech-training", "LoungeTech Training Cloud", "Education & careers", "Provider operations, training cohorts and evidence", "evidence", "confirmed"],
  ["loungetech-founders", "LoungeTech Gründungsportal", "Professional services", "Business formation cases, documents and partner coordination", "documents", "confirmed"],
  [
    "zarvane",
    "Zarvane",
    "Food & hospitality",
    "Trade rice supply, orders, samples and bulk quotations",
    "commerce",
    "confirmed",
  ],
  [
    "haccora",
    "Haccora",
    "Food & hospitality",
    "Food safety, corrective actions and inspection evidence",
    "evidence",
    "confirmed",
  ],
  [
    "dokuvera",
    "Dokuvera",
    "Property & construction",
    "Controlled documents, revisions and evidence packs",
    "documents",
    "confirmed",
  ],
  [
    "omniqora",
    "Omniqora",
    "Communications",
    "Customer conversations, cases and follow-ups",
    "inbox",
    "confirmed",
  ],
  [
    "taxnuvia",
    "TaxNuvia",
    "Professional services",
    "Qualified client intake for accountant matching",
    "intake",
    "confirmed",
  ],
  [
    "eventplanr",
    "EventPlanr",
    "Marketplaces",
    "Event briefs, supplier quotations and coordination",
    "quotes",
    "confirmed",
  ],
  [
    "kinderstars",
    "KinderStars",
    "Family & care",
    "Parent enquiries and independent childminder administration",
    "intake",
    "confirmed",
  ],
  [
    "ahlnikkah",
    "AhlNikkah",
    "Family & care",
    "Introductions, compatibility workbooks and family coordination",
    "coordination",
    "confirmed",
  ],
  [
    "affivon",
    "Affivon",
    "Commerce",
    "Catalogue and offer operations for multiple affiliate websites",
    "commerce",
    "confirmed",
  ],
  [
    "merqora",
    "Merqora",
    "Commerce",
    "Marketplace seller operations, listings and margin review",
    "commerce",
    "confirmed",
  ],
  [
    "premisora",
    "Premisora",
    "Property & construction",
    "Construction projects, options and change control",
    "projects",
    "confirmed",
  ],
  [
    "gabley",
    "Gabley",
    "Property & construction",
    "Survey and property information",
    "documents",
    "confirmed",
  ],
  [
    "gabley-retrofit",
    "Gabley Retrofit",
    "Property & construction",
    "Retrofit planning, delivery evidence and warranties",
    "projects",
    "confirmed",
  ],
  [
    "domureva",
    "DOMUREVA",
    "Property & construction",
    "Vacant property restoration and funding evidence",
    "projects",
    "confirmed",
  ],
  [
    "immoviq",
    "Immoviq",
    "Property & construction",
    "Landlord and tenant maintenance operations",
    "coordination",
    "confirmed",
  ],
  [
    "hmo-flow",
    "HMO Flow",
    "Property & construction",
    "HMO conversion and property records",
    "projects",
    "confirmed",
  ],
  [
    "craftvaro",
    "Craftvaro",
    "Property & construction",
    "Trade jobs, subcontractors and project delivery",
    "quotes",
    "confirmed",
  ],
  [
    "cirqiva",
    "Cirqiva",
    "Marketplaces",
    "Waste collection quotations and collection evidence",
    "quotes",
    "confirmed",
  ],
  [
    "marktpass",
    "MarktPass",
    "Commerce",
    "Product compliance documents for Germany and EU sellers",
    "documents",
    "confirmed",
  ],
  [
    "merqano",
    "Merqano",
    "Commerce",
    "Independent merchant storefront operations",
    "commerce",
    "confirmed",
  ],
  [
    "dishbee",
    "Dishbee",
    "Food & hospitality",
    "EPOS, online ordering and restaurant operations",
    "commerce",
    "confirmed",
  ],
  [
    "schonova",
    "Schonova",
    "Marketplaces",
    "Beauty discovery, bookings and provider operations",
    "coordination",
    "confirmed",
  ],
  [
    "xpertjobs",
    "XpertJobs",
    "Education & careers",
    "Jobs, sponsor intelligence and application coordination",
    "intake",
    "confirmed",
  ],
  [
    "unipathways",
    "UniPathways",
    "Education & careers",
    "Learning and certification preparation",
    "coordination",
    "confirmed",
  ],
  [
    "traindirekt",
    "TrainDirekt",
    "Education & careers",
    "Training cohorts, attendance and evidence",
    "evidence",
    "confirmed",
  ],
  [
    "lessonahead",
    "LessonAhead",
    "Education & careers",
    "Learner enquiries and session coordination",
    "coordination",
    "confirmed",
  ],
  [
    "kalethon-play",
    "Kalethon Play",
    "Education & careers",
    "Sports sessions, memberships and venue bookings",
    "coordination",
    "confirmed",
  ],
  [
    "nearcura",
    "NearCura",
    "Family & care",
    "Healthcare provider discovery and enquiries",
    "intake",
    "confirmed",
  ],
  [
    "amityos",
    "AmityOS",
    "Family & care",
    "Care provider staffing, visits, finance and organisation administration",
    "coordination",
    "confirmed",
  ],
  [
    "pipkin",
    "Pipkin",
    "Family & care",
    "Care SaaS; detailed product scope to review",
    "coordination",
    "review",
  ],
  [
    "taxcenda",
    "TaxCenda",
    "Professional services",
    "Bookkeeping and tax document preparation",
    "documents",
    "confirmed",
  ],
  [
    "lawquo",
    "LawQuo",
    "Professional services",
    "Professional legal enquiries and consultation coordination",
    "intake",
    "confirmed",
  ],
  [
    "beratermarkt",
    "BeraterMarkt",
    "Professional services",
    "Adviser discovery and enquiry coordination",
    "intake",
    "confirmed",
  ],
  [
    "beistandplus",
    "BeistandPlus",
    "Family & care",
    "Family and administrative case coordination",
    "coordination",
    "confirmed",
  ],
  [
    "orvilo",
    "Orvilo",
    "Creative & websites",
    "Website structure, template and content preparation",
    "content",
    "confirmed",
  ],
  [
    "voxentri",
    "Voxentri",
    "Creative & websites",
    "Multilingual advertising content and production",
    "content",
    "confirmed",
  ],
  [
    "veyumo",
    "Veyumo",
    "Communications",
    "Mobile service onboarding and customer support",
    "inbox",
    "confirmed",
  ],
  [
    "zoryn-pay",
    "Zoryn Pay",
    "Payments & rewards",
    "Payment reconciliation and onboarding evidence",
    "evidence",
    "confirmed",
  ],
  [
    "zoryn-rewards",
    "Zoryn Rewards",
    "Payments & rewards",
    "Loyalty programme operations and support",
    "inbox",
    "confirmed",
  ],
  [
    "insure360",
    "Insure360",
    "Professional services",
    "Insurance enquiries, documents and renewal coordination",
    "intake",
    "confirmed",
  ],
  [
    "motoresq",
    "MotoResQ",
    "Transport & logistics",
    "Vehicle recovery enquiries and coordination",
    "coordination",
    "confirmed",
  ],
  [
    "all-road-aid",
    "All-Road-Aid",
    "Transport & logistics",
    "Roadside assistance and recovery requests",
    "coordination",
    "confirmed",
  ],
  [
    "fleetsora",
    "Fleetsora",
    "Transport & logistics",
    "Fleet and rider operations",
    "coordination",
    "confirmed",
  ],
  [
    "fanzeno",
    "Fanzeno",
    "Education & careers",
    "Sports quiz content and quality review",
    "content",
    "confirmed",
  ],
  [
    "auvane-one",
    "Auvane One",
    "Marketplaces",
    "Hospitality and service supplier onboarding",
    "intake",
    "confirmed",
  ],
  [
    "leadlens",
    "LeadLens",
    "Professional services",
    "Opportunity discovery and qualification",
    "intake",
    "confirmed",
  ],
  [
    "regulos",
    "Regulos",
    "Professional services",
    "Regulatory change review and task allocation",
    "documents",
    "confirmed",
  ],
  [
    "threeonethree",
    "ThreeOneThree",
    "Communications",
    "CRM and opportunity follow-up",
    "inbox",
    "confirmed",
  ],
  [
    "loungeconnect",
    "LoungeConnect",
    "Communications",
    "Messages, customer cases and workflow coordination",
    "inbox",
    "confirmed",
  ],
  [
    "rettio",
    "Rettio",
    "Marketplaces",
    "Local business workflows; product scope to review",
    "coordination",
    "review",
  ],
  [
    "kiezio",
    "Kiezio",
    "Marketplaces",
    "Local commerce workflows; product scope to review",
    "coordination",
    "review",
  ],
  [
    "syndryvia",
    "Syndryvia",
    "Scope to review",
    "Product name recovered; functionality needs confirmation",
    "coordination",
    "review",
  ],
  [
    "skillfinch",
    "Skillfinch",
    "Education & careers",
    "Employer training bookings, trainer operations and learning evidence",
    "evidence",
    "confirmed",
  ],
  [
    "stemcoach",
    "STEMCoach",
    "Scope to review",
    "Product functionality needs confirmation",
    "coordination",
    "review",
  ],
  [
    "criclume",
    "Criclume",
    "Scope to review",
    "Product functionality needs confirmation",
    "coordination",
    "review",
  ],
  [
    "formationgenie",
    "FormationGenie",
    "Scope to review",
    "Product functionality needs confirmation",
    "coordination",
    "review",
  ],
  [
    "recovarable",
    "Recovarable",
    "Scope to review",
    "Product functionality needs confirmation",
    "coordination",
    "review",
  ],
  [
    "depotmesh",
    "DepotMesh",
    "Scope to review",
    "Validation-stage product; scope needs confirmation",
    "coordination",
    "review",
  ],
  [
    "gradlume",
    "Gradlume",
    "Scope to review",
    "Training-engine concept; detailed scope to review",
    "coordination",
    "review",
  ],
  [
    "dearnext",
    "DearNext",
    "Scope to review",
    "Earlier platform; detailed scope to review",
    "coordination",
    "review",
  ],
  [
    "construction-planning",
    "AI Construction Planning",
    "Property & construction",
    "Design options and change proposals for professional review",
    "projects",
    "confirmed",
  ],
  [
    "portfolio-network",
    "Portfolio network",
    "Payments & rewards",
    "Consented cross-product referrals and bundle rules",
    "intake",
    "confirmed",
  ],
];
export const portfolioProducts = rows.map((r) => ({
  slug: r[0],
  name: r[1],
  sector: r[2],
  description: r[3],
  scope: r[5],
}));
